### ISSUE TITLE
Automate updating the Wishlist issues 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/eng-automation#11]
This is about writing a simple GHA to automate updating the comments in https://github.com/paritytech/polkadot-sdk/issues/3900 and https://github.com/paritytech/polkadot-sdk/issues/3901

I used the python script in https://github.com/kianenigma/wishlist-tracker and it seems to work. What would be great to write a GHA that would run every 24h, and update my first comment every night. The original python script has the code to update the README of the repo as an example.

**Comment by rzadp** [comment]
Makes sense, I don't have any questions - we'll do it.

**Comment by rzadp** [comment]
@kianenigma Proposed https://github.com/paritytech/polkadot-sdk/pull/5085

**Comment by rzadp** [comment]
The wishlists are now automatically updated.

## Before

![Screenshot 2024-07-25 at 10 15 11](https://github.com/user-attachments/assets/d57df1f9-7a16-4718-a303-e278082b0743)

---

![Screenshot 2024-07-25 at 10 15 21](https://github.com/user-attachments/assets/88db23b1-478a-49b6-bfdc-2c5ecb56e37e)

## After

![Screenshot 2024-07-25 at 11 12 59](https://github.com/user-attachments/assets/0c364a37-eebf-499a-89a9-56359d61779a)

![Screenshot 2024-07-25 at 11 13 32](https://github.com/user-attachments/assets/7ce5d07b-7569-475d-88c2-17e816529563)
