### ISSUE TITLE
Automate the hash generation and PR closing/merging for Fellows' Evidences

### ISSUE THREAD

**Issue by rzadp** [paritytech/eng-automation#9]
The [Evidences](https://github.com/polkadot-fellows/Evidences) project will have an analogous process to the RFC process - a text containing evidence of work, an OpenGov referendum with the hash of that text, and PR merging depending on the outcome of the referendum.

We can help with this, and we can start with a fork of the [rfc-action](https://github.com/paritytech/rfc-action).

https://github.com/polkadot-fellows/Evidences/issues/4

**Comment by mordamax** [comment]
Seems like is superseded by https://github.com/polkadot-fellows/Evaluations/issues/15
